# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bwi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opFrom', models.DateTimeField(blank=True, null=True)),
                ('opTo', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='division',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='pettycashentry',
            name='divisionId',
        ),
        migrations.RemoveField(
            model_name='pettycashreceipt',
            name='divisionId',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='User',
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.Division'),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.UserProfile'),
        ),
        migrations.AddField(
            model_name='pettycashreceipt',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.Division'),
        ),
        migrations.AddField(
            model_name='pettycashreceipt',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.Company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.Division'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashreceipt',
            name='entryNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationaltransaction',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.Division'),
        ),
        migrations.AddField(
            model_name='operationaltransaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwi.UserProfile'),
        ),
    ]
