# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwi', '0003_auto_20170718_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='receiptNo',
            new_name='receiptNumber',
        ),
    ]
