# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwi', '0008_auto_20170726_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaltransaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operationaltransaction',
            name='cutomerName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], default='Mr.', max_length=5),
        ),
        migrations.AlterField(
            model_name='operationaltransaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='divisions',
            field=models.ManyToManyField(to='bwi.Division'),
        ),
    ]
